### ISSUE TITLE
curl -i http://localhost:23456/minerList

### ISSUE THREAD

**Issue by joshmatix** [Daemon-Technologies/Mining-Monitor#4]
After seeing
node server.js -t /tmp/stacks-testnet-2005d8d0f11f76c7
Example app listening at http://localhost:23456

I gave this command:
curl -i http://localhost:23456/minerList

I got the following:
tom@tom-mate:~/Mining-Monitor$ curl -i http://localhost:23456/minerList
HTTP/1.1 404 Not Found
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With
Access-Control-Allow-Methods: PUT,POST,GET,DELETE,OPTIONS
Access-Control-Allow-Credentials: true
Content-Security-Policy: default-src 'none'
X-Content-Type-Options: nosniff
Content-Type: text/html; charset=utf-8
Content-Length: 149
Date: Mon, 14 Dec 2020 23:52:27 GMT
Connection: keep-alive
Keep-Alive: timeout=5

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /minerList</pre>
</body>
</html>

**Comment by tyGavinZJU** [comment]
Latest api is /mining_info
Please refer to http://monitor.stxmining.xyz/mining_info
